#
# This file is generated.  Do not edit this file.
# You lose your edits the next time it is generated.
#
export PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/sdk-utilities-0.0.0-2019.08.0:/E/FreedomStudio-2019-08-2-win64/SiFive/riscv64-unknown-elf-gcc-8.3.0-2019.08.0/bin:$PATH
export FREEDOM_STUDIO_INSTALL_PATH=/E/FreedomStudio-2019-08-2-win64
export FREEDOM_STUDIO_TOOLCHAIN_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/riscv64-unknown-elf-gcc-8.3.0-2019.08.0/bin
export FREEDOM_STUDIO_MSYS_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/msys64-1.0.0-2019.05.2/usr/bin
export FREEDOM_STUDIO_PROJECT_NAME=RTOSDemo
export FREEDOM_STUDIO_PROJECT_PATH=/E/private/hifive1-revb/print/FreeRTOS/Demo/RISC-V_RV32_SiFive_HiFive1_FreedomStudio
export FREEDOM_STUDIO_OPENOCD=openocd.exe
export FREEDOM_STUDIO_OPENOCD_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/riscv-openocd-0.10.0-2019.08.2/bin
export FREEDOM_STUDIO_QEMU=qemu-system-riscv32.exe
export FREEDOM_STUDIO_QEMU_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/riscv-qemu-4.1.0-2019.08.0/bin
export FREEDOM_STUDIO_TRACE_DECODER=dqr.exe
export FREEDOM_STUDIO_TRACE_DECODER_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/trace-decoder-0.0.0-2019.08.0
export FREEDOM_STUDIO_GDB=riscv64-unknown-elf-gdb.exe
export FREEDOM_SDK_TOOLS_PATH=/E/FreedomStudio-2019-08-2-win64/SiFive/sdk-utilities-0.0.0-2019.08.0
